- name: Boostrap application server
  hosts: applications
  gather_facts: no
  vars:
    username: "{{ lookup('env', 'HL_USERNAME') }}"
    tunnel_token: "{{ lookup('env', 'CF_TUNNEL_TOKEN') }}"
    portainer_api_key: "{{ lookup('env', 'PORTAINER_API_KEY') }}"
  pre_tasks:
    - name: Make sure required environment variables are set
      assert:
        that:
          - username != ""
          - portainer_api_key != ""
          - tunnel_token != ""
        fail_msg: 'Some required environment variables are not set'
  tasks:
    - name: Set hostname
      ansible.builtin.hostname:
        name: jupiter

    - name: Replace raspberrypi hostname in /etc/hosts
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '(\s+)raspberrypi(\s+.*)?$'
        replace: '\1jupiter\2'

    - name: Restart avahi-daemon
      ansible.builtin.systemd:
        state: restarted
        name: avahi-daemon

    - name: Update and dist upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker and compose plugin
      ansible.builtin.apt:
        pkg:
          - docker.io
          - docker-compose-v2

    - name: Make sure the Docker group exists
      ansible.builtin.group:
        name: docker
        state: present

    - name: Add user to Docker group
      ansible.builtin.user:
        name: "{{ username }}"
        append: true
        groups:
          - docker

    - name: Copy compose file
      ansible.builtin.copy:
        src: ./compose-files/applications/docker-compose.yml
        dest: "/home/{{ username }}/docker-compose.yml"

    - name: Create .env file for docker compose
      ansible.builtin.file:
        path: "/home/{{ username }}/.env"
        state: touch

    - name: Populate .env file with necessary variables
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.env"
        content: |
          TUNNEL_TOKEN={{ tunnel_token }} 

    - name: Copy NGINX configuration file
      ansible.builtin.copy:
        src: ./configs/nginx/jupiter.conf
        dest: "/home/{{ username }}/jupiter.conf"

    - name: Copy WNRS JSON levels
      ansible.builtin.copy:
        src: ./assets/wnrs-levels.json
        dest: "/home/{{ username }}/wnrs.json"

    - name: Copy logo image
      ansible.builtin.copy:
        src: ./assets/logo.png
        dest: "/home/{{ username }}/logo.png"

    - name: Copy dashboard configuration file
      ansible.builtin.copy:
        src: ./configs/dashboards/homer.yml
        dest: "/home/{{ username }}/dashboard.yml"

    - name: Replace Portainer API Key in dashboard configuration
      ansible.builtin.replace:
        path: "/home/{{ username }}/dashboard.yml"
        regexp: '\$PORTAINER_API_KEY'
        replace: "{{ portainer_api_key }}"

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: "/home/{{ username }}/"
        project_name: "jupiter"
        remove_orphans: true
        recreate: "always"
