services:
  # site:
  #   container_name: site
  #   image: aloussase/site:latest
  #   restart: unless-stopped
  #   ports: 
  #     - "3000:8080"
  #

  dashboard:
    container_name: dashboard
    image: b4bz/homer
    ports:
      - "3001:8080"
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./jupiter.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=jupiter.local
      - NGINX_PORT=80

  tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
