services:
  site:
    container_name: site
    image: aloussase/site:latest
    restart: unless-stopped
    platform: linux/amd64
    ports: 
      - "3000:8080"

  issues-aggregator-backend:
    container_name: issues-aggregator-backend
    image: aloussase/gh-api-bff:latest
    restart: unless-stopped
    env_file: ".env"
    environment:
      PORT: 6900 
    ports:
      - "6900:6900"

  issues-aggregator-frontend:
    container_name: issues-aggregator-frontend
    image: aloussase/gh-api-mf:latest
    restart: unless-stopped
    ports:
      - "6901:6901"

  dashboard:
    container_name: dashboard
    image: b4bz/homer
    ports:
      - "3001:8080"
    restart: unless-stopped
    volumes:
      - ./dashboard.yml:/www/assets/config.yml
      - ./logo.png:/www/assets/logo.png

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./jupiter.conf:/etc/nginx/conf.d/default.conf
      - ./wnrs.json:/etc/nginx/files/wnrs-levels.json
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=jupiter.local
      - NGINX_PORT=80

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run

volumes:
  portainer-data: {}
