services:
  # site:
  #   container_name: site
  #   image: aloussase/site:latest
  #   restart: unless-stopped
  #   ports: 
  #     - "3000:8080"

  tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
